site_name: Disseny d'Interfícies Web

nav:
  - Inici: index.md
  - Unitats de Treball:
    - UT8 - Portafolis Web:
      - Introducció i Context: unitats/ut8/index.md
      - Planificació i Organització:
        - Planificació de Sessions: unitats/ut8/planificacio-sessions.md
        - Indicacions per l'Alumnat: unitats/ut8/indicacions-especifiques.md
        - Desplegament AWS Academy: unitats/ut8/desplegament-aws.md
      - Avaluació:
        - Sistema d'Avaluació: unitats/ut8/avaluacio.md
      - Recursos i Eines:
        - Recursos Generats: unitats/ut8/recursos-generats.md
        - Eines Descobertes: unitats/ut8/eines-descobertes.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
    heading: Roboto
    monospace: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: purple
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - md_in_html
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format