name: ci

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instal·la dependències
        run: |
          pip install mkdocs-material
          pip install pymdown-extensions

      - name: Dona permisos d'execució al script
        run: chmod +x build.sh

      - name: Executa build.sh
        run: |
          ./build.sh
          echo "Verificant site/DIW..."
          ls -la site/DIW || (echo "❌ Error: site/DIW no s'ha creat" && exit 1)

      - name: Guarda els fitxers generats temporalment
        run: |
          cp -r site /tmp/site_backup
          echo "✅ Fitxers guardats a /tmp/site_backup"
          ls -la /tmp/site_backup/

      - name: Prepara git per desplegar
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git reset --hard

      - name: Canvia a la branca gh-pages
        run: |
          git fetch origin gh-pages --depth=1 || true
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Esborra contingut antic (excepte .git)
        run: |
          find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +

      - name: Copia els fitxers generats
        run: |
          if [ -d /tmp/site_backup ]; then
            cp -r /tmp/site_backup/* .
            echo "✅ Fitxers copiats correctament"
            ls -la
          else
            echo "❌ ERROR: La carpeta site/ no existeix"
            exit 1
          fi

      - name: Puja a GitHub Pages
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No hi ha canvis a desplegar"
          else
            git commit -m "Deploy docs from ${GITHUB_SHA}"
            git push origin gh-pages
          fi