name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build all subprojects
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Deploy to GitHub Pages
        run: |
          git fetch origin gh-pages --depth=1 || true
          git checkout gh-pages || git checkout --orphan gh-pages
          find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +
          cp -r site/* .
          git add .
          if git diff --staged --quiet; then
            echo "No changes to deploy"
          else
            git commit -m "Deploy docs from ${GITHUB_SHA}"
            git push origin gh-pages
          fi